version: "3"
services:
  web-development:
    # container_name: web
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /mnt/f/Bootcamps/Tools Pack/Docker and Kubernetes/Section-6-Workflow/frontend/node_modules
      - .:/home/node/app

  web-testing:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /mnt/f/Bootcamps/Tools Pack/Docker and Kubernetes/Section-6-Workflow/frontend/node_modules
      - .:/home/node/app
    command: ["npm", "run", "test"]
