name: Deploy Frontend
on:
  push:
    branches:
      - main
jobs:
  build:
    # GitHub-hosted runner using the "ubuntu-latest" virtual machine image. It has docker installed by default
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t anhtuan/react-test -f Dockerfile.dev .

      # Environment variable: -e CI=true; startup command: npm test
      - run: docker run -e CI=true anhtuan/react-test npm test

      - name: Generate deployment package
        # Compresses all files and directories in the current directory into a ZIP archive named deploy.zip.
        # Excludes any files ending with .git. (-x flag means exclude)
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}

          region: ap-southeast-2

          # Elastic Beanstalk
          application_name: frontend
          environment_name: Frontend-env

          # S3 Bucket
          existing_bucket_name: elasticbeanstalk-ap-southeast-2-663177864709

          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
